### ISSUE TITLE
add support for provider image deletion

### ISSUE THREAD

**Issue by jprovaznik** [aeolus-incubator/tim#64] opened 2012-11-28 13:06 UTC
It would be nice to destroy provider image on provider side when the image is being destroyed.

**Comment by jguiditta** [comment] 2012-12-04 14:59
This looks like a duplicate of issue #59, is there anything here that is not covered there?

**Comment by jguiditta** [comment] 2012-12-10 14:40
Closing this, due to no disagreement on my above comment

**Closed as completed by jguiditta** 2012-12-10 14:40 UTC
